apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: weather-server-deployment
  name: weather-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-server-deployment
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: weather-server-deployment
    spec:
      containers:
        - image: nickmurdock/weather-server:1.0
          name: weather-server
          resources: { }
          ports:
            - containerPort: 8080
          volumeMounts:
           - mountPath: /env/.env
             subPath: .env
             name: config-map
             readOnly: true
      volumes:
        - name: config-map
          configMap:
            name: server-config
status: { }
